# Generated by Django 5.2.5 on 2025-10-07 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=127)),
                ('fat', models.FloatField(default=0)),
                ('saturatedFat', models.FloatField(default=0)),
                ('transFat', models.FloatField(default=0)),
                ('cholesterol', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('sugars', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('potassium', models.FloatField(default=0)),
                ('magnesium', models.FloatField(default=0)),
                ('phosphorus', models.FloatField(default=0)),
                ('zinc', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('vitaminC', models.FloatField(default=0)),
                ('vitaminD', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('age', models.PositiveIntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('percentConsumed', models.FloatField(default=1)),
                ('foodItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fooditem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.profile')),
            ],
        ),
    ]
