# Generated by Django 5.2.5 on 2025-10-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fdcId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
