# Generated by Django 5.2.6 on 2025-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_fooditem_fdcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='fdcId',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
