# Generated by Django 5.2.5 on 2025-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_profile_birthdate_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='foodName',
            field=models.CharField(max_length=255),
        ),
    ]
